package helpers;

import com.github.javafaker.Faker;

/**
 * FakeUserData class provides constants FIRST_NAME, LAST_NAME, POST_CODE.
 * These constants generated by methods which use library Faker.
 * <a href="https://github.com/DiUS/java-faker">DiUS/java-faker</a>
 */
public class FakeUserData {

    /**
     * Initialize Faker class instance.
     */
    static Faker faker = new Faker();

    /**
     * The FIRST_NAME constant contains a first name, collected from the getFirstName() method.
     */
    public static final String FIRST_NAME = getFirstName();

    /**
     * The LAST_NAME constant contains a last name, collected from the getLastName() method.
     */
    public static final String LAST_NAME = getLastName();

    /**
     * The POST_CODE constant contains a post code, collected from the getPostCode() method.
     */
    public static final String POST_CODE = getPostCode();

    /**
     * This method provide a first name, generated by Faker library.
     */
    public static String getFirstName() {
        return faker.name().firstName();
    }

    /**
     * This method provide a last name, generated by Faker library.
     */
    public static String getLastName() {
        return faker.name().lastName();
    }

    /**
     * This method provide a post code, generated by Faker Library.
     */
    public static String getPostCode() {
        return faker.address().zipCode();
    }
}
