package helpers;

import com.github.javafaker.Faker;

/**
 * FakeUserData class provides constants FIRST_NAME, LAST_NAME, POST_CODE.
 * These constants generated by methods which use library Faker.
 * <a href="https://github.com/DiUS/java-faker">DiUS/java-faker</a>
 */
public class FakeUserData {
    static Faker faker = new Faker();

    public static final String FIRST_NAME = getFirstName();

    public static final String LAST_NAME = getLastName();

    public static final String POST_CODE = getPostCode();

    /**
     * This method return a generated first name
     */
    public static String getFirstName() {
        return faker.name().firstName();
    }

    /**
     * This method return a generated last name
     */
    public static String getLastName() {
        return faker.name().lastName();
    }

    /**
     * This method return a generated post code
     */
    public static String getPostCode() {
        return faker.address().zipCode();
    }
}
